stages:
  - building
  - test

gcc:
  stage: building
  script:
    - mkdir build
    - cd build
    - cmake -G "Unix Makefiles"
      -DCMAKE_C_COMPILER=gcc
      -DCMAKE_CXX_COMPILER=g++
      -DCMAKE_BUILD_TYPE=Release
      -DTEST=true
      ..
    - cmake --build .
  artifacts:
    paths:
      - build/main_tests

clang:
  stage: building
  script:
    - mkdir build
    - cd build
    - cmake -G "Unix Makefiles"
      -DCMAKE_C_COMPILER=clang
      -DCMAKE_CXX_COMPILER=clang++
      -DCMAKE_BUILD_TYPE=Release
      -DTEST=true
      ..
    - cmake --build .
  artifacts:
    paths:
      - build/main_tests

google-gcc:
  stage: test
  dependencies:
    - gcc
  script:
    - ./build/main_tests

google-clang:
  stage: test
  dependencies:
    - clang
  script:
    - ./build/main_tests
