build:
  script:
  - git submodule init
  - git submodule update
  - ./compile.sh
  - ./build/main_tests
  after_script:
  - cd /media/storage/gitlab/
  - rm -rf GoogleTest_Example
  - git clone http://git.home.lan/root/GoogleTest_Example.git
  - cd GoogleTest_Example
  - git submodule init
  - git submodule update
